### ISSUE TITLE
Argument 2 passed to Symfony\Component\HttpKernel\EventListener\ProfilerListener::__construct() must be an instance of Symfony\Component\HttpFoundation\RequestStack, null given

### ISSUE THREAD

**Issue by cnkt** [silexphp/Silex-WebProfiler#74]
I've run `composer update` and see this error:

![screen shot 2015-10-10 at 09 29 53](https://cloud.githubusercontent.com/assets/447973/10409649/8c3618ac-6f31-11e5-8354-fa795c003a1f.png)

I have this two dependencies in composer.json related to silex:

```
"silex/silex": "~1.3",
"silex/web-profiler": "1.0.x-dev"
```

**Comment by adrianguenter** [comment]
I presume you've solved this, but for anyone else who winds up here: check `minimum-stability` and `prefer-stable` in your `composer.json`.

I had `"minimum-stability": "beta"` and `"prefer-stable": false`, which was causing Composer to pull the `v3.0.0-BETA1` tag of `symfony/http-kernel` instead of `^2.7`. In Symfony 2.8 the last argument of the `ProfilerListener` constructor (`RequestStack $requestStack = null`) was moved forward into position two of the argument list, and had its default value/nullable trait removed (the reason for the relocation, I'd guess).

**Comment by zago89** [comment]
I had  same problem, it´s was  update silex and composer automatically update to ```` "symfony/http-kernel" : "~3.0" ```` since that is a dependency of ````symfony/web-profiler-bundle```` and I didn't have another to limit manually the version of ````"symfony/http-kernel" : "<3.0"````
